### ISSUE TITLE
Simple %-formatting missed

### ISSUE THREAD

**Issue by nedbat** [asottile/pyupgrade#431] opened 2021-05-02 21:58 UTC
I ran `pyupgrade --py36-plus` on a file of mine in coverage.py. It converted some formatting to f-strings, but skipped a number of simple %-formatting instances.

Here's the file with a particular chunk highlighted: https://github.com/nedbat/coveragepy/blob/b74461aef05559e17da555c20f4ce63c610e9307/coverage/cmdline.py#L756-L799

I used pyupgrade 2.14.0

**Comment by asottile** [comment] 2021-05-02 22:08
duplicate of #78 #256 #337 #367

tl;dr: it's impossible to safely determine what it should be rewritten to because the variable of a 1-ary format could be a scalar `'%s' % x` => `'{}'.format(x)` or it could be a tuple: `'%s' % x` => `'%s'.format(*x)` -- this is one of my primary motivations to *never* use %-format

**Closed by asottile** 2021-05-02 22:08 UTC

**Comment by asottile** [comment] 2021-05-02 22:11
additionally, %d cannot be safely converted either because it involves an implicit call to `int(...)` which would ~generally be worse after "upgrading"
