### ISSUE TITLE
Fix collection literals and comprehensions like `flake-comprehensions`

### ISSUE THREAD

**Issue by Zac-HD** [asottile/pyupgrade#228] opened 2019-12-09 06:25 UTC
[`flake8-comprehensions`](https://pypi.org/project/flake8-comprehensions/) is a lovely plugin to warn about inefficient creation of and operations on collections - and each of the warnings suggests a simple rewrite rule to resolve them.  

I'm not sure if this is really in scope for `pyupgrade`, but it's similar enough to the existing literals/comprehensions functionality that I thought it was worth suggesting.

**Comment by asottile** [comment] 2019-12-09 08:22
This is a dupe of #31 and out of scope I'm afraid

`dict(**...)` might in the future be rewritten to `{**...}` but generically rewriting `dict(...)` isn't quite in the spirit

**Closed by asottile** 2019-12-09 08:22 UTC
