### ISSUE TITLE
Use `pyproject.toml` `requires-python` field to guess Python target

### ISSUE THREAD

**Issue by Tpt** [asottile/pyupgrade#795] opened 2023-02-06 10:37 UTC
First, thank you for your very nice tool!

A quick thought if you might be interested: it could be nice to use [the `pyproject.toml`  `requires-python` field](https://peps.python.org/pep-0621/#requires-python) to automatically infer the correct `--pyXX-plus` option to use.

**Comment by hugovk** [comment] 2023-02-06 10:43
It's a good idea and the new [Black 23.1.0 does it](https://ichard26.github.io/blog/2023/01/black-23.1.0/#better-default-for---target-version-if-pep-621-python-requires-is-available), but this is a duplicate of https://github.com/asottile/pyupgrade/issues/688:

> no thanks -- that would involve reading configuration files of which I don't want anything to do with that complexity

https://github.com/asottile/pyupgrade/issues/688#issuecomment-1200443121

**Closed** 2023-02-06 10:56 UTC
