### ISSUE TITLE
Suggestion: rewrite python2 styles annotations to python3 styles

### ISSUE THREAD

**Issue by bluebird75** [asottile/pyupgrade#459] opened 2021-06-04 08:22 UTC
Those #type: int  are annoying, could pyupgrade handle that ?

**Comment by MarcoGorelli** [comment] 2021-06-04 08:27
Hi @bluebird75 - dupe of #410 , #403 ?

**Closed** 2021-06-04 14:15 UTC

**Comment by bluebird75** [comment] 2021-06-04 18:38
indeed; sorry for missing it.
