### ISSUE TITLE
Remove typing imports when performing pep 585 typing rewrites

### ISSUE THREAD

**Issue by mathbunnyru** [asottile/pyupgrade#517] opened 2021-08-11 17:03 UTC
The code like this:
```
from typing import List
  
def f(l: List[str]) -> None:
    print(l)
```

becomes

```
from typing import List
  
def f(l: list[str]) -> None:
    print(l)
```

So, we get an unused import.

One option - is to give this job to `autoflake` (maybe it's worth mentioning).
Another - do the cleanup here.

**Comment by MarcoGorelli** [comment] 2021-08-11 18:14
Hi @mathbunnyru - this is a duplicate of #391

**Closed** 2021-08-11 18:38 UTC

**Comment by mathbunnyru** [comment] 2021-08-11 18:39
Sorry, thanks!
