### ISSUE TITLE
Assertion failure while visiting `Name` node whose context is not `Load` or `Store`

### ISSUE THREAD

**Issue by ptpan** [asottile/pyupgrade#307] opened 2020-05-17 00:20 UTC
Pyupgrade 2.4.2 fails an assertion at 
```
  File "~/.virtualenvs/<env-name>/lib/python3.6/site-packages/pyupgrade.py", line 1454, in visit_Name
    raise AssertionError(node)
```
while analyzing the following the code snippet 
``` python
class CaseDeleteComp:
  class DUT( Component ):
    def construct( s ):
      @update
      def upblk():
        del u
```
where as the name `u` is in two function scopes and has `Del` context.

Seems like the current implementation does not really care about non-load/store contexts in these situations. Is it possible to allow for non-load/store contexts here?

**Comment by asottile** [comment] 2020-05-17 00:25
dupe of #306

**Closed by asottile** 2020-05-17 00:25 UTC
