### ISSUE TITLE
Simple %-string not re-written ?

### ISSUE THREAD

**Issue by Carreau** [asottile/pyupgrade#256] opened 2020-02-07 18:18 UTC
I've read the readme and the warning:

```
note: pyupgrade is intentionally timid and will not create an f-string if it would make the expression longer or if the substitution parameters are anything but simple names or dotted names (as this can decrease readability).
```

I'm though curious as to why this is not re-written ?

```
def run():
    abcd = "1234"
    print('abcd: %s' % abcd)
    print('abcd: {abcd}')
```

The f-string seem to be shorter and more readable.

It looks like %-format with a single formatter are not rewritten.

I don't have any issues with it; it can be a reasonable choice; just wondering if that's on purpose.

**Comment by asottile** [comment] 2020-02-07 18:22
duplicate of #78

**Closed by asottile** 2020-02-07 18:22 UTC

**Comment by Carreau** [comment] 2020-02-07 18:37
Thanks.
